import { Dish } from './types';

export const DISHES_PER_PAGE = 12;

export const TRANSLATIONS = {
  en: {
    restaurantName: "Lumière",
    restaurantNameZh: "光",
    seasonalMenu: "Seasonal Tasting Menu",
    chefsSpecial: "Chef's Special",
    yourSelection: "Your Selection",
    clear: "Clear",
    closeSelection: "Close Selection",
    sendOrder: "Send Order",
    orderHistory: "Order History",
    noOrders: "No past orders.",
    orderPlaced: "Order sent successfully!",
    deleteOrderConfirm: "Are you sure you want to delete this order record?",
    orderId: "Order #",
    items: "items",
    total: "Total",
    delete: "Delete",
    personalList: "Alan's customized menu, exclusive for private use.",
    menuManagement: "Menu Management",
    addDish: "Add Dish",
    import: "Import",
    export: "Export",
    cuisine: "Cuisine",
    dishName: "Dish Name",
    description: "Description...",
    videoUrl: "Video URL",
    spiciness: "Spiciness:",
    sweetness: "Sweetness:",
    featured: "Featured",
    directory: "Directory",
    emptyCart: "Your selection is empty.",
    noDishes: "No enabled dishes to display.",
    deleteConfirm: "Are you sure you want to delete this dish?",
    untitled: "Untitled",
    newSection: "New Section",
    newDish: "New Dish",
    toggleVisibility: "Toggle Visibility",
    watchVideo: "Watch Video",
    thinking: "Thinking...",
    aiPolish: "AI Polish",
    importSummaryTitle: "Import Summary",
    importSuccess: "Import Successful",
    itemsAdded: "Added",
    itemsUpdated: "Updated",
    cuisineBreakdown: "Cuisine Breakdown",
    newBadge: "New",
    updateBadge: "Upd",
    close: "Close",
    errorInvalidJson: "Invalid file format: Expected a JSON array of dishes.",
    errorParsing: "Error parsing JSON file. Please check the file for syntax errors."
  },
  zh: {
    restaurantName: "Lumière",
    restaurantNameZh: "光",
    seasonalMenu: "季节性品鉴菜单",
    chefsSpecial: "主厨推荐",
    yourSelection: "已选菜品",
    clear: "清空",
    closeSelection: "关闭列表",
    sendOrder: "发送订单",
    orderHistory: "历史订单",
    noOrders: "暂无历史订单。",
    orderPlaced: "订单已发送！",
    deleteOrderConfirm: "确定要删除这条订单记录吗？",
    orderId: "订单号",
    items: "件",
    total: "共",
    delete: "删除",
    personalList: "阿兰定制菜单，私人专享",
    menuManagement: "菜单管理",
    addDish: "添加菜品",
    import: "导入",
    export: "导出",
    cuisine: "菜系",
    dishName: "菜名",
    description: "描述...",
    videoUrl: "视频链接",
    spiciness: "辣度:",
    sweetness: "甜度:",
    featured: "推荐",
    directory: "目录",
    emptyCart: "购物车为空。",
    noDishes: "暂无可用菜品。",
    deleteConfirm: "确定要删除这道菜吗？",
    untitled: "未命名",
    newSection: "新分类",
    newDish: "新菜品",
    toggleVisibility: "切换可见性",
    watchVideo: "观看视频",
    thinking: "思考中...",
    aiPolish: "AI 润色",
    importSummaryTitle: "导入摘要",
    importSuccess: "导入成功",
    itemsAdded: "新增",
    itemsUpdated: "更新",
    cuisineBreakdown: "菜系详情",
    newBadge: "新",
    updateBadge: "更",
    close: "关闭",
    errorInvalidJson: "文件格式无效：需要菜品 JSON 数组。",
    errorParsing: "解析 JSON 文件出错。请检查文件语法。"
  }
};

export const INITIAL_DISHES: Dish[] = [];